//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionPlanner.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامترهای پیشرفته.
        /// </summary>
        public static string AdvancedParams {
            get {
                return ResourceManager.GetString("AdvancedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید که می خواهید آپلود کنید؟ .
        /// </summary>
        public static string AreYouSureYouWantToUpload {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرواز خودکار.
        /// </summary>
        public static string AutoWP {
            get {
                return ResourceManager.GetString("AutoWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Battery.
        /// </summary>
        public static string Bad_Battery {
            get {
                return ResourceManager.GetString("Bad_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad KML File :.
        /// </summary>
        public static string Bad_KML_File {
            get {
                return ResourceManager.GetString("Bad_KML_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Proximity.
        /// </summary>
        public static string Bad_Proximity {
            get {
                return ResourceManager.GetString("Bad_Proximity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad SatCom.
        /// </summary>
        public static string Bad_SatCom {
            get {
                return ResourceManager.GetString("Bad_SatCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت دید نامناسب.
        /// </summary>
        public static string Bad_Vision_Position {
            get {
                return ResourceManager.GetString("Bad_Vision_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سنسور شتاب سنج پهپاد.
        /// </summary>
        public static string BadAccelHealth {
            get {
                return ResourceManager.GetString("BadAccelHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ای.اچ.آر.اس پهپاد.
        /// </summary>
        public static string BadAHRS {
            get {
                return ResourceManager.GetString("BadAHRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhealthy Airspeed.
        /// </summary>
        public static string BadAirspeed {
            get {
                return ResourceManager.GetString("BadAirspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سنسور فشارهوا پهپاد.
        /// </summary>
        public static string BadBaroHealth {
            get {
                return ResourceManager.GetString("BadBaroHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سنسور قطب نما پهپاد.
        /// </summary>
        public static string BadCompassHealth {
            get {
                return ResourceManager.GetString("BadCompassHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Lat/Lng.
        /// </summary>
        public static string BadCoords {
            get {
                return ResourceManager.GetString("BadCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های جی پی اس با اختلال همراه است.
        /// </summary>
        public static string BadGPSHealth {
            get {
                return ResourceManager.GetString("BadGPSHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سنسور ژیروسکوپ پهپاد.
        /// </summary>
        public static string BadGyroHealth {
            get {
                return ResourceManager.GetString("BadGyroHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سنسور رادار پهپاد.
        /// </summary>
        public static string BadLiDARHealth {
            get {
                return ResourceManager.GetString("BadLiDARHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Logging.
        /// </summary>
        public static string BadLogging {
            get {
                return ResourceManager.GetString("BadLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سنسور رادار خطی پهپاد.
        /// </summary>
        public static string BadOptFlowHealth {
            get {
                return ResourceManager.GetString("BadOptFlowHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم وجود داده های زمین شناسی .
        /// </summary>
        public static string BadorNoTerrainData {
            get {
                return ResourceManager.GetString("BadorNoTerrainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیم اولیه.
        /// </summary>
        public static string BasicTuning {
            get {
                return ResourceManager.GetString("BasicTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بتا.
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اینها سیستم عامل بتا هستند، با مسئولیت خود استفاده کنید!!!.
        /// </summary>
        public static string BetaWarning {
            get {
                return ResourceManager.GetString("BetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمی توان به پورت com متصل شد و نوع برد را تشخیص داد.
        /// </summary>
        public static string CanNotConnectToComPortAnd {
            get {
                return ResourceManager.GetString("CanNotConnectToComPortAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این فیلد را نمی توان نمودار کرد.
        /// </summary>
        public static string CannotGraphField {
            get {
                return ResourceManager.GetString("CannotGraphField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمی‌توان نسخه برد شما را شناسایی کرد. لطفا کابل کشی خود را بررسی کنید.
        /// </summary>
        public static string CantDetectBoardVersion {
            get {
                return ResourceManager.GetString("CantDetectBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر سرعت.
        /// </summary>
        public static string ChangeThrottle {
            get {
                return ResourceManager.GetString("ChangeThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درحال بررسی کردن .
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات پورت اتصال را بررسی کنید.
        /// </summary>
        public static string CheckPortSettingsOr {
            get {
                return ResourceManager.GetString("CheckPortSettingsOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگامی که انجام شد کلیک کنید.
        /// </summary>
        public static string Click_when_Done {
            get {
                return ResourceManager.GetString("Click_when_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمان اجرا نشد
        ///.
        /// </summary>
        public static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ارتباط – اتصال انجام نشد.
        /// </summary>
        public static string CommunicationErrorNoConnection {
            get {
                return ResourceManager.GetString("CommunicationErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واریانس قطب نما.
        /// </summary>
        public static string compass_variance {
            get {
                return ResourceManager.GetString("compass_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل شد.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصال.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصال.
        /// </summary>
        public static string CONNECTc {
            get {
                return ResourceManager.GetString("CONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصال به پهپاد ناموفق بود.
        /// </summary>
        public static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال اتصال به پهپاد.
        /// </summary>
        public static string ConnectingMavlink {
            get {
                return ResourceManager.GetString("ConnectingMavlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادامه .
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting bin to log.
        /// </summary>
        public static string Converting_bin_to_log {
            get {
                return ResourceManager.GetString("Converting_bin_to_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح: .
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسایی شده است .
        /// </summary>
        public static string DetectedA {
            get {
                return ResourceManager.GetString("DetectedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشخیص نسخه برد.
        /// </summary>
        public static string DetectingBoardVersion {
            get {
                return ResourceManager.GetString("DetectingBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطع اتصال.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم اتصال.
        /// </summary>
        public static string DISCONNECTc {
            get {
                return ResourceManager.GetString("DISCONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا می خواهید این را در صفحه داده های پرواز بارگیری کنید؟.
        /// </summary>
        public static string Do_you_want_to_load_this_into_the_flight_data_screen {
            get {
                return ResourceManager.GetString("Do_you_want_to_load_this_into_the_flight_data_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام شد.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از اینترنت دانلود شده.
        /// </summary>
        public static string DownloadedFromInternet {
            get {
                return ResourceManager.GetString("DownloadedFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود از اینترنت.
        /// </summary>
        public static string DownloadingFromInternet {
            get {
                return ResourceManager.GetString("DownloadingFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطمینان حاصل کنید ملخ ها به پهپاد متصل نمی باشد.
        /// </summary>
        public static string EnsurePropsNotOn {
            get {
                return ResourceManager.GetString("EnsurePropsNotOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام تنظیمات شما در طول به روز رسانی از بین می رود، آیا می خواهید ادامه دهید؟.
        /// </summary>
        public static string EppromChanged {
            get {
                return ResourceManager.GetString("EppromChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epprom format changed ({0) vs {1}).
        /// </summary>
        public static string EppromFormatChanged {
            get {
                return ResourceManager.GetString("EppromFormatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در اتصال.
        /// </summary>
        public static string Error_binding {
            get {
                return ResourceManager.GetString("Error_binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بستن فایل های گزارش.
        /// </summary>
        public static string ErrorClosingLogFile {
            get {
                return ResourceManager.GetString("ErrorClosingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در برقراری ارتباط با خلبان خودکار.
        /// </summary>
        public static string ErrorCommunicating {
            get {
                return ResourceManager.GetString("ErrorCommunicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در اتصال
        ///.
        /// </summary>
        public static string ErrorConnecting {
            get {
                return ResourceManager.GetString("ErrorConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این ویژگی در سیستم خلبان خودکار شما فعال نیست.
        /// </summary>
        public static string ErrorFeatureNotEnabled {
            get {
                return ResourceManager.GetString("ErrorFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بارگیری فایل سیستم عامل.
        /// </summary>
        public static string ErrorFirmwareFile {
            get {
                return ResourceManager.GetString("ErrorFirmwareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در دریافت لیست گزارش.
        /// </summary>
        public static string ErrorLogList {
            get {
                return ResourceManager.GetString("ErrorLogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا: پاسخی از تلمتری لینک پهپاد دریافت نشد.
        /// </summary>
        public static string ErrorNoResponce {
            get {
                return ResourceManager.GetString("ErrorNoResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما متصل نمی باشید.
        /// </summary>
        public static string ErrorNotConnected {
            get {
                return ResourceManager.GetString("ErrorNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در دریافت لیست
        ///.
        /// </summary>
        public static string ErrorReceivingParams {
            get {
                return ResourceManager.GetString("ErrorReceivingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا: دستور توسط پهپاد دریافت نشد.
        /// </summary>
        public static string ErrorRejectedByMAV {
            get {
                return ResourceManager.GetString("ErrorRejectedByMAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در تغییر نام فایل.
        /// </summary>
        public static string ErrorRenameFile {
            get {
                return ResourceManager.GetString("ErrorRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در تنظیم پارامترها .
        /// </summary>
        public static string ErrorSettingParameter {
            get {
                return ResourceManager.GetString("ErrorSettingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با خطا مواجه شد {0} تنظیم.
        /// </summary>
        public static string ErrorSetValueFailed {
            get {
                return ResourceManager.GetString("ErrorSetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در آپلود سیستم عامل.
        /// </summary>
        public static string ErrorUploadingFirmware {
            get {
                return ResourceManager.GetString("ErrorUploadingFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات تکمیلی.
        /// </summary>
        public static string ExtendedTuning {
            get {
                return ResourceManager.GetString("ExtendedTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت گزارش ایجاد نشد.
        /// </summary>
        public static string Failclog {
            get {
                return ResourceManager.GetString("Failclog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to SITL instance.
        /// </summary>
        public static string Failed_to_connect_to_SITL_instance {
            get {
                return ResourceManager.GetString("Failed_to_connect_to_SITL_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download the SITL image..
        /// </summary>
        public static string Failed_to_download_the_SITL_image {
            get {
                return ResourceManager.GetString("Failed_to_download_the_SITL_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود انجام نشد.
        /// </summary>
        public static string FailedDownload {
            get {
                return ResourceManager.GetString("FailedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX خوانده نشد.
        /// </summary>
        public static string FailedReadHEX {
            get {
                return ResourceManager.GetString("FailedReadHEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.hex خوانده نشد:.
        /// </summary>
        public static string FailedToReadHex {
            get {
                return ResourceManager.GetString("FailedToReadHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپلود ناموفق.
        /// </summary>
        public static string FailedUpload {
            get {
                return ResourceManager.GetString("FailedUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailSafe.
        /// </summary>
        public static string FailSafe {
            get {
                return ResourceManager.GetString("FailSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالت های پرواز.
        /// </summary>
        public static string FlightModes {
            get {
                return ResourceManager.GetString("FlightModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست کامل پارامترها.
        /// </summary>
        public static string FullParameterList {
            get {
                return ResourceManager.GetString("FullParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درختواره کامل پارامترها.
        /// </summary>
        public static string FullParameterTree {
            get {
                return ResourceManager.GetString("FullParameterTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ژئوفنس.
        /// </summary>
        public static string GeoFence {
            get {
                return ResourceManager.GetString("GeoFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقض جغرافیایی.
        /// </summary>
        public static string GeofenceBreach {
            get {
                return ResourceManager.GetString("GeofenceBreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درحال دریافت.
        /// </summary>
        public static string Getting {
            get {
                return ResourceManager.GetString("Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست فریمورها.
        /// </summary>
        public static string GettingFWList {
            get {
                return ResourceManager.GetString("GettingFWList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست نسخه های فریمور.
        /// </summary>
        public static string GettingFWVersion {
            get {
                return ResourceManager.GetString("GettingFWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات پهپاد .
        /// </summary>
        public static string GettingParams {
            get {
                return ResourceManager.GetString("GettingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات پهپاد ....
        /// </summary>
        public static string GettingParamsD {
            get {
                return ResourceManager.GetString("GettingParamsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت پارامترهای به روز شده.
        /// </summary>
        public static string GettingUpdatedParams {
            get {
                return ResourceManager.GetString("GettingUpdatedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات .
        /// </summary>
        public static string Gotparam {
            get {
                return ResourceManager.GetString("Gotparam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت مکانی خانه نامعتبر است.
        /// </summary>
        public static string Invalid_home_location {
            get {
                return ResourceManager.GetString("Invalid_home_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Location.
        /// </summary>
        public static string Invalid_Location {
            get {
                return ResourceManager.GetString("Invalid_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتفاع وارد شده نامعتبر است.
        /// </summary>
        public static string InvalidAlt {
            get {
                return ResourceManager.GetString("InvalidAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرخ بادریت وارد شده نامعتبر است.
        /// </summary>
        public static string InvalidBaudRate {
            get {
                return ResourceManager.GetString("InvalidBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع برد نامعتبر است.
        /// </summary>
        public static string InvalidBoardType {
            get {
                return ResourceManager.GetString("InvalidBoardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Cert.
        /// </summary>
        public static string InvalidCert {
            get {
                return ResourceManager.GetString("InvalidCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد وارد شده نامعتبر است.
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فایل وارد شده نامعتبر است.
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد وارد شده نامعتبر است
        ///.
        /// </summary>
        public static string InvalidNumberEntered {
            get {
                return ResourceManager.GetString("InvalidNumberEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدوده پن وارد شده نامعتبر است.
        /// </summary>
        public static string InvalidPanRange {
            get {
                return ResourceManager.GetString("InvalidPanRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پورت وارد شده نامعتبر است.
        /// </summary>
        public static string InvalidPortName {
            get {
                return ResourceManager.GetString("InvalidPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدوده تیل وارد شده نامعتبر است.
        /// </summary>
        public static string InvalidTiltRange {
            get {
                return ResourceManager.GetString("InvalidTiltRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرخ بروزرسانی نامعتبر است.
        /// </summary>
        public static string InvalidUpdateRate {
            get {
                return ResourceManager.GetString("InvalidUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت لینک تلمتری.
        /// </summary>
        public static string LinkStats {
            get {
                return ResourceManager.GetString("LinkStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری داده ها.
        /// </summary>
        public static string Load_data {
            get {
                return ResourceManager.GetString("Load_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً روی اوکی کلیک کنید و خلبان خودکار را حول تمام محورها به صورت دایره ای حرکت دهید.
        /// </summary>
        public static string MagCalibMsg {
            get {
                return ResourceManager.GetString("MagCalibMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAVFtp.
        /// </summary>
        public static string MAVFtp {
            get {
                return ResourceManager.GetString("MAVFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درحال اتصال به پهپاد ....
        /// </summary>
        public static string MavlinkConnecting {
            get {
                return ResourceManager.GetString("MavlinkConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما نقاط داده را از دست داده اید. آیا به هر حال می خواهید کالیبراسیون را اجرا کنید؟.
        /// </summary>
        public static string MissingDataPoints {
            get {
                return ResourceManager.GetString("MissingDataPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستم عامل جدید.
        /// </summary>
        public static string NewFirmware {
            get {
                return ResourceManager.GetString("NewFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستم عامل جدید موجود شد
        ///.
        /// </summary>
        public static string NewFirmwareA {
            get {
                return ResourceManager.GetString("NewFirmwareA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No firmware available for this board!.
        /// </summary>
        public static string No_firmware_available_for_this_board {
            get {
                return ResourceManager.GetString("No_firmware_available_for_this_board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ سیگنال معتبری از پورت خوانده نشد.
        /// </summary>
        public static string No_valid_heartbeats_read_from_port {
            get {
                return ResourceManager.GetString("No_valid_heartbeats_read_from_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid sik radio.
        /// </summary>
        public static string No_valid_sik_radio {
            get {
                return ResourceManager.GetString("No_valid_sik_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ پیامی موجود نمی باشد: .
        /// </summary>
        public static string NoFMTMessage {
            get {
                return ResourceManager.GetString("NoFMTMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need to upload. already on the board.
        /// </summary>
        public static string NoNeedToUpload {
            get {
                return ResourceManager.GetString("NoNeedToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rc Found.
        /// </summary>
        public static string NORCReceiver {
            get {
                return ResourceManager.GetString("NORCReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available when used as a windows store app.
        /// </summary>
        public static string Not_available_when_used_as_a_windows_store_app {
            get {
                return ResourceManager.GetString("Not_available_when_used_as_a_windows_store_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توجه.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain From Module.
        /// </summary>
        public static string ObtainFromModule {
            get {
                return ResourceManager.GetString("ObtainFromModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبول.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboard OSD.
        /// </summary>
        public static string OnboardOSD {
            get {
                return ResourceManager.GetString("OnboardOSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط یک سیگنال دریافت شد.
        /// </summary>
        public static string Only1Hb {
            get {
                return ResourceManager.GetString("Only1Hb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط یک سیگنال از این پورت خوانده شد - تأیید کنید که سخت افزار شما به درستی تنظیم شده است
        ///نرم افزار قبل از اتصال منتظر دو سیگنال معتبر است
        ///.
        /// </summary>
        public static string Only1HbD {
            get {
                return ResourceManager.GetString("Only1HbD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Param refresh is required - Please press F5
        ///old #{0}  new #{1}.
        /// </summary>
        public static string ParamRefreshRequired {
            get {
                return ResourceManager.GetString("ParamRefreshRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string Planner {
            get {
                return ResourceManager.GetString("Planner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ابتدا به پهپاد متصل شوید.
        /// </summary>
        public static string PleaseConnect {
            get {
                return ResourceManager.GetString("PleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً پیکربندی خود را در برگه پیکربندی وصل کرده و پشتیبان بگیرید..
        /// </summary>
        public static string PleaseConnectAndBackupConfig {
            get {
                return ResourceManager.GetString("PleaseConnectAndBackupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک فایل معتبر بارگذاری کنید.
        /// </summary>
        public static string PleaseLoadValidFile {
            get {
                return ResourceManager.GetString("PleaseLoadValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ابتدا یک سلول را انتخاب کنید.
        /// </summary>
        public static string PleaseSelectCell {
            get {
                return ResourceManager.GetString("PleaseSelectCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً برد را از برق بکشید و سپس OK را فشار دهید و دوباره وصل کنید.
        ///برنامه ریز ماموریت به مدت 30 ثانیه برای یافتن تخته جستجو می کند.
        /// </summary>
        public static string PleaseUnplugTheBoardAnd {
            get {
                return ResourceManager.GetString("PleaseUnplugTheBoardAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///لطفا ارتقا دهید.
        /// </summary>
        public static string Pleaseup {
            get {
                return ResourceManager.GetString("Pleaseup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the musical tones to finish before clicking OK.
        /// </summary>
        public static string PleaseWaitForTheMusicalTones {
            get {
                return ResourceManager.GetString("PleaseWaitForTheMusicalTones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واریانس موقعیت افقی.
        /// </summary>
        public static string pos_horiz_variance {
            get {
                return ResourceManager.GetString("pos_horiz_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واریانس موقعیت عمودی.
        /// </summary>
        public static string pos_vert_variance {
            get {
                return ResourceManager.GetString("pos_vert_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت پروگرام شد.
        /// </summary>
        public static string ProgrammedOK {
            get {
                return ResourceManager.GetString("ProgrammedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put the transmitter in bind mode. Receiver is waiting..
        /// </summary>
        public static string Put_the_transmitter_in_bind_mode__Receiver_is_waiting {
            get {
                return ResourceManager.GetString("Put_the_transmitter_in_bind_mode__Receiver_is_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار پارامترها.
        /// </summary>
        public static string RawParamWarning {
            get {
                return ResourceManager.GetString("RawParamWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام مقادیر موجود در این صفحه حداقل/حداکثر بررسی نشده اند. لطفا ورودی خود را دوباره بررسی کنید. لطفاً از پارامترهای استاندارد/پیشرفته برای تنظیمات ایمن استفاده کنید.
        /// </summary>
        public static string RawParamWarningi {
            get {
                return ResourceManager.GetString("RawParamWarningi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Hex.
        /// </summary>
        public static string ReadingHex {
            get {
                return ResourceManager.GetString("ReadingHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Hex File.
        /// </summary>
        public static string ReadingHexFile {
            get {
                return ResourceManager.GetString("ReadingHexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست دریافت شد.
        /// </summary>
        public static string ReceivedList {
            get {
                return ResourceManager.GetString("ReceivedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به هر حال اجرا کنید.
        /// </summary>
        public static string RunAnyway {
            get {
                return ResourceManager.GetString("RunAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درحال ذخیره کردن.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بررسی فایل.
        /// </summary>
        public static string Scanning_File {
            get {
                return ResourceManager.GetString("Scanning_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک پورت اتصال انتخاب کنید.
        /// </summary>
        public static string SelectComport {
            get {
                return ResourceManager.GetString("SelectComport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اینجا را تنظیم کنید.
        /// </summary>
        public static string SetHere {
            get {
                return ResourceManager.GetString("SetHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا دوباره نمایش داده شود؟.
        /// </summary>
        public static string ShowMeAgain {
            get {
                return ResourceManager.GetString("ShowMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامترهای استاندارد.
        /// </summary>
        public static string StandardParams {
            get {
                return ResourceManager.GetString("StandardParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع .
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پهپاد شما هنوز در حال پرواز است آیا مطمئن هستید که می خواهید ارتباط را قطع کنید؟.
        /// </summary>
        public static string Stillmoving {
            get {
                return ResourceManager.GetString("Stillmoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوقف کردن.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واریانس ارتفاعی زمین.
        /// </summary>
        public static string terrain_alt_variance {
            get {
                return ResourceManager.GetString("terrain_alt_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This board has been retired, Mission Planner this will upload the last available version to your board (AC 3.2.1/AP 3.4.0).
        /// </summary>
        public static string ThisBoardHasBeenRetired {
            get {
                return ResourceManager.GetString("ThisBoardHasBeenRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان انتظار برای اسکن خودکار به پایان رسیده است.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker Home.
        /// </summary>
        public static string TrackerHome {
            get {
                return ResourceManager.GetString("TrackerHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trunk.
        /// </summary>
        public static string Trunk {
            get {
                return ResourceManager.GetString("Trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the latest trunk firmware, use at your own risk!!!.
        /// </summary>
        public static string TrunkWarning {
            get {
                return ResourceManager.GetString("TrunkWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال تلاش برای اتصال
        /// {0}.
        /// </summary>
        public static string Trying {
            get {
                return ResourceManager.GetString("Trying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units: {0}{1}.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به روز رسانی پیدا شد
        ///
        ///آیا می خواهید اکنون به روز رسانی کنید؟ .
        /// </summary>
        public static string UpdateFound {
            get {
                return ResourceManager.GetString("UpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به روز رسانی در دسترس نیست..
        /// </summary>
        public static string UpdateNotFound {
            get {
                return ResourceManager.GetString("UpdateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکنون به روز رسانی کن.
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپلود کامل شد.
        /// </summary>
        public static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading {0} bytes to Board:.
        /// </summary>
        public static string UploadingBytesToBoard {
            get {
                return ResourceManager.GetString("UploadingBytesToBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload succeeded, but verify failed: exp {0} got {1} at .
        /// </summary>
        public static string UploadSucceededButVerifyFailed {
            get {
                return ResourceManager.GetString("UploadSucceededButVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Params.
        /// </summary>
        public static string User_Params {
            get {
                return ResourceManager.GetString("User_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واریانس سرعت.
        /// </summary>
        public static string velocity_variance {
            get {
                return ResourceManager.GetString("velocity_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید کامل شد.
        /// </summary>
        public static string VerifyComplete {
            get {
                return ResourceManager.GetString("VerifyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فریمور را تأیید کنید.
        /// </summary>
        public static string VerifyFirmware {
            get {
                return ResourceManager.GetString("VerifyFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, as of AC 3.1 motors will spin when armed, configurable through the MOT_SPIN_ARMED parameter.
        /// </summary>
        public static string WarningAC31 {
            get {
                return ResourceManager.GetString("WarningAC31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, if you are installing AC 3.2 for the first time you MUST redo a Compass calibration..
        /// </summary>
        public static string WarningAC32 {
            get {
                return ResourceManager.GetString("WarningAC32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Browse بدون پیام های FMT در گزارش شما به درستی عمل نمی کند.
        ///به نظر می رسد این موارد در گزارش شما وجود ندارد..
        /// </summary>
        public static string WarningLogBrowseFMTMissing {
            get {
                return ResourceManager.GetString("WarningLogBrowseFMTMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning rally points are located greater than RALLY_LIMIT_KM.
        /// </summary>
        public static string Warningrallypointdistance {
            get {
                return ResourceManager.GetString("Warningrallypointdistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به روز رسانی پارامترها
        ///اگر در هوا هستید این کار را نکنید
        ///.
        /// </summary>
        public static string WarningUpdateParamList {
            get {
                return ResourceManager.GetString("WarningUpdateParamList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using unsupported hardware.
        ///This board does not contain a valid certificate of authenticity.
        ///Please contact your hardware vendor about signing your hardware..
        /// </summary>
        public static string YouAreUsingUnsupportedHardware {
            get {
                return ResourceManager.GetString("YouAreUsingUnsupportedHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزرگنمایی.
        /// </summary>
        public static string Zoom_To {
            get {
                return ResourceManager.GetString("Zoom_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زوم به مرکز یا فایل بارگذاری شده؟.
        /// </summary>
        public static string Zoom_to_the_center_or_the_loaded_file {
            get {
                return ResourceManager.GetString("Zoom_to_the_center_or_the_loaded_file", resourceCulture);
            }
        }
    }
}
